package:
  name: pandas
  version: 1.1.4

source:
  url: https://files.pythonhosted.org/packages/09/39/fb93ed98962d032963418cd1ea5927b9e11c4c80cb1e0b45dea769d8f9a5/pandas-1.1.4.tar.gz
  sha256: a979d0404b135c63954dea79e6246c45dd45371a88631cdbb4877d844e6de3b6

build:
  cflags: -Wno-implicit-function-declaration

requirements:
  run:
    - numpy
    - python-dateutil
    - pytz

test:
  imports:
    - pandas
