name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install bzip2 libgconf-2-4 node-less node-commander cmake build-essential clang-format-6.0 chromium-bsu ccache libncurses5-dev gfortran f2c swig g++-8 python3.8
        sudo apt-get clean
        sudo apt-get autoremove
    - name: Test node
      run: |
        which node
        test $(which node) = /usr/local/bin/node || exit 1
    - name: Test uglifyjs
      run: |
        sudo npm install -g uglify-js
        which uglifyjs
        test $(which uglifyjs) = /usr/local/bin/uglifyjs || exit 1
        head /usr/local/bin/uglifyjs
    - name: Fix node path in script uglifyjs
      run: |
        sudo sed -i 's|/usr/bin/env node|/usr/local/bin/node|g' /usr/local/bin/uglifyjs
        head /usr/local/bin/uglifyjs
        echo '"use strict";' > /tmp/test.js
        echo 'var hello = "world";' >> /tmp/test.js
        /usr/local/bin/uglifyjs /tmp/test.js || echo "uglifyjs failed"
    - name: Install python dependencies
      run: |
        sudo pip install pytest pytest-xdist pytest-instafail pytest-rerunfailures pytest-httpserver selenium PyYAML flake8
        sudo rm -rf /root/.cache/pip
    - name: Make
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: Build output
        path: build
