name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bzip2 libgconf-2-4 node-less cmake build-essential clang-format-6.0 chromium-bsu ccache libncurses5-dev gfortran f2c swig g++-8 python3.8
        sudo apt-get clean
        sudo apt-get autoremove
    - name: Test node and uglifyjs
      run: |
        which node
        test $(which node) = /usr/local/bin/node || exit 1
        sudo npm install commander -g
        sudo npm install uglify-js -g
        echo '"use strict";' > /tmp/test.js
        echo 'var hello = "world";' >> /tmp/test.js
        /usr/local/bin/uglifyjs /tmp/test.js
    - name: Install python dependencies
      run: |
        sudo pip install pytest pytest-xdist pytest-instafail pytest-rerunfailures pytest-httpserver selenium PyYAML flake8
        sudo rm -rf /root/.cache/pip
    - name: Make
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: Build output
        path: build
